### PR TITLE
Fix: Removed pixi.js-legacy and canvas from devDependencies and added them to dependencies

### PR DESCRIPTION
**Pull request by SmartArray**
This PR adds required dependencies to the correct section in package.json.

Otherwise those would be removed when installing this library in production environment

### CODE REVIEW

**Comment by SmartArray** [comment]
Proper way would be adding them to the peerDependencies...

**Comment by Prozi** [comment]
why would this be beneficial in any way?

```
jacekp@pop-os:~/projects/pietal$ yarn add pixi-shim
yarn add v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 4 new dependencies.
info Direct dependencies
└─ pixi-shim@2.3.25
info All dependencies
├─ entities@4.3.1
├─ jsdom-global@3.0.2
├─ jsdom@20.0.0
└─ pixi-shim@2.3.25
Done in 6.57s.
```

installing pixi-shim doesnt add either canvas or pixi.js-legacy to your dependencies

it's for tests, required for development, hence in devDependencies

@SmartArray

**Comment by SmartArray** [comment]
If `pixi-shim` is installed using `npm ci --production`, it won't include `pixi.js-legacy`, will it?
I assume `pixi.js-legacy` is required in production environments and not only in tests?

**Comment by Prozi** [comment]
when you do npm i pixi-shim

it doesnt install pixi.js-legacy or canvas

it doesnt need them to work

please close this mr :-)

**Comment by SmartArray** [comment]
Can you explain why it doesn't need the deps? https://github.com/Prozi/pixi-shim/blob/b8e77bd51a06cbb6696330c6abd97fa463386e9f/pixi.js#L11

**Comment by Prozi** [comment]
> Can you explain why it doesn't need the deps?
> 
> https://github.com/Prozi/pixi-shim/blob/b8e77bd51a06cbb6696330c6abd97fa463386e9f/pixi.js#L11

the default import doesnt need either pixi nor canvas

when you want pixijs actual usage like filters etc you need to install canvas and pixi and pixi legacy

i will include this in the readme thank you for pointing this out !!

**Comment by Prozi** [comment]
related: 
https://github.com/Prozi/pixi-shim#usage-if-your-gameapp-is-feature-heavy

**Pull request closed without merging**
